### ISSUE TITLE
Issue in this kernel 

### ISSUE THREAD

**Issue by mixpunkload** [F1xy-kernels/SURYA_kernel#2]
This kernel was not able to put in evolution x 5.9 and corvus 16.7 there was a logo freeze problem and stay on starting logo of custom os PLZZ resolved this problem sir and iam using poco x3 sir.

**Comment by PXblaZe** [comment]
Yeah I also flashed it on ArrowOs and PE+ but as you said it freezes on logo screen.

**Comment by YaroST12** [comment]
The last update to this kernel was in April, fuck off.
